patch:
  schema_list:
    - schema: luna_pinyin          # 朙月拼音
    - schema: luna_pinyin_simp     # 朙月拼音 简化字模式
    - schema: double_pinyin        # 自然碼雙拼
    - schema: double_pinyin_flypy  # 小鶴雙拼
    - schema: emoji         # emoji表情
